"use client"

import { useMemo, useState } from "react"
import { Button } from "@/components/ui/button"
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select"
import { Download, Eye, Loader2 } from "lucide-react"

type Props = {
  driverId: string
  driverName: string
  printerSlugs: string[]
  executionPrototype: string | null
}

function detectBasePath(): string {
  if (typeof window === "undefined") return ""
  return window.location.pathname.startsWith("/foomatic-lookup-site") ? "/foomatic-lookup-site" : ""
}

function sanitizeFileName(s: string): string {
  return s.replace(/[^a-zA-Z0-9._-]+/g, "_").replace(/_+/g, "_")
}

function limitTo39(s: string): string {
  return s.length <= 39 ? s : s.slice(0, 39)
}

function buildMinimalPpd(opts: {
  make: string
  model: string
  printerSlug: string
  driverId: string
  driverName: string
  executionPrototype: string | null
  guiTextsLimitedTo39: boolean
}): string {
  const manufacturer = opts.make || "Unknown"
  const modelName = `${opts.make} ${opts.model}`.trim() || "Unknown"
  const nick = `${modelName} - ${opts.driverName}`.trim()

  const pcFileNameRaw = `${opts.printerSlug}-${opts.driverName}.ppd`
  const pcFileName = sanitizeFileName(pcFileNameRaw).toUpperCase()

  const ModelName = opts.guiTextsLimitedTo39 ? limitTo39(modelName) : modelName
  const NickName = opts.guiTextsLimitedTo39 ? limitTo39(nick) : nick

  return [
    `*PPD-Adobe: "4.3"`,
    `*% PPD generated by foomatic-lookup-site (static export)`,
    opts.guiTextsLimitedTo39
      ? `*% Note: GUI texts limited to 39 characters`
      : `*% Note: GUI texts NOT limited to 39 characters`,
    `*FormatVersion: "4.3"`,
    `*FileVersion: "1.0"`,
    `*LanguageVersion: English`,
    `*LanguageEncoding: ISOLatin1`,
    `*PCFileName: "${pcFileName}"`,
    `*Manufacturer: "${manufacturer}"`,
    `*ModelName: "${ModelName}"`,
    `*NickName: "${NickName}"`,
    `*ShortNickName: "${opts.model || opts.printerSlug}"`,
    `*Product: "(${modelName})"`,
    `*cupsVersion: "1.1"`,
    `*cupsManualCopies: True`,
    `*% Driver ID: ${opts.driverId}`,
    `*% Printer ID: printer/${opts.printerSlug}`,
    opts.executionPrototype ? `*% Execution prototype: ${opts.executionPrototype}` : `*% Execution prototype: (none)`,
    ``,
    `*OpenUI *PageSize/Media Size: PickOne`,
    `*DefaultPageSize: A4`,
    `*PageSize A4/A4: "<</PageSize[595 842]>>setpagedevice"`,
    `*PageSize Letter/US Letter: "<</PageSize[612 792]>>setpagedevice"`,
    `*CloseUI: *PageSize`,
    ``,
    `*OpenUI *Resolution/Resolution: PickOne`,
    `*DefaultResolution: 600dpi`,
    `*Resolution 600dpi/600 dpi: ""`,
    `*CloseUI: *Resolution`,
    ``,
    `*% This is a lightweight placeholder PPD. Full Foomatic-generated PPD output is not yet implemented in this site.`,
    ``,
  ].join("\n")
}

export default function DriverPpdTools({
  driverId,
  driverName,
  printerSlugs,
  executionPrototype,
}: Props) {
  const printers = useMemo(
    () =>
      [...printerSlugs].sort((a, b) => a.localeCompare(b)).map((slug) => ({
        slug,
        label: slug.replace(/-/g, " ").replace(/_/g, " "),
      })),
    [printerSlugs]
  )

  const [selectedPrinter, setSelectedPrinter] = useState<string>(printers[0]?.slug ?? "")
  const [guiTextsLimitedTo39, setGuiTextsLimitedTo39] = useState(false)
  const [ppdText, setPpdText] = useState<string>("")
  const [busy, setBusy] = useState(false)
  const [error, setError] = useState<string | null>(null)

  async function generatePpd(): Promise<string | null> {
    if (!selectedPrinter) return null

    setBusy(true)
    setError(null)
    try {
      const basePath = detectBasePath()
      const res = await fetch(
        `${basePath}/foomatic-db/printers/${encodeURIComponent(selectedPrinter)}.json`
      )
      if (!res.ok) {
        throw new Error(`Failed to load printer data (${res.status})`)
      }
      const data = await res.json()
      const make: string = data?.printer?.make ?? selectedPrinter.split("-")[0] ?? "Unknown"
      const model: string =
        data?.printer?.model ?? selectedPrinter.split("-").slice(1).join("-") ?? selectedPrinter

      const ppd = buildMinimalPpd({
        make,
        model,
        printerSlug: selectedPrinter,
        driverId,
        driverName,
        executionPrototype,
        guiTextsLimitedTo39,
      })

      setPpdText(ppd)
      return ppd
    } catch (e) {
      const msg = e instanceof Error ? e.message : "Failed to generate PPD"
      setError(msg)
      setPpdText("")
      return null
    } finally {
      setBusy(false)
    }
  }

  async function onView() {
    await generatePpd()
  }

  async function onDownload() {
    const ppd = (ppdText && ppdText.includes("*PPD-Adobe")) ? ppdText : await generatePpd()
    if (!ppd) return

    const filename = sanitizeFileName(`${selectedPrinter}-${driverName}.ppd`)
    const blob = new Blob([ppd], { type: "text/plain;charset=utf-8" })
    const url = URL.createObjectURL(blob)
    try {
      const a = document.createElement("a")
      a.href = url
      a.download = filename
      document.body.appendChild(a)
      a.click()
      a.remove()
    } finally {
      URL.revokeObjectURL(url)
    }
  }

  if (printers.length === 0) return null

  return (
    <div className="space-y-3">
      <div className="flex flex-col sm:flex-row items-start sm:items-end gap-3">
        <div className="w-full sm:w-64 space-y-1">
          <label className="block text-sm font-medium text-foreground">Select printer:</label>
          <Select
            value={selectedPrinter}
            onValueChange={(v) => { setSelectedPrinter(v); setPpdText(""); setError(null) }}
          >
            <SelectTrigger className="w-full">
              <SelectValue placeholder="Choose a printer…" />
            </SelectTrigger>
            <SelectContent>
              {printers.map((p) => (
                <SelectItem key={p.slug} value={p.slug}>
                  {p.label}
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
        </div>

        <div className="flex flex-wrap items-center gap-2">
          <Button
            variant="outline"
            size="sm"
            onClick={onDownload}
            disabled={busy || !selectedPrinter}
            className="gap-2"
          >
            {busy ? <Loader2 className="h-4 w-4 animate-spin" /> : <Download className="h-4 w-4" />}
            download
          </Button>
          <Button
            variant="outline"
            size="sm"
            onClick={onView}
            disabled={busy || !selectedPrinter}
            className="gap-2"
          >
            {busy ? <Loader2 className="h-4 w-4 animate-spin" /> : <Eye className="h-4 w-4" />}
            display the PPD file
          </Button>
        </div>
      </div>

      <label className="flex items-center gap-2 text-sm text-muted-foreground">
        <input
          type="checkbox"
          checked={guiTextsLimitedTo39}
          onChange={(e) => setGuiTextsLimitedTo39(e.target.checked)}
          className="h-4 w-4 accent-primary"
        />
        GUI texts limited to 39 characters
      </label>

      {error ? <p className="text-sm text-destructive">{error}</p> : null}

      {ppdText ? (
        <details className="rounded-lg border border-border/50 bg-muted/30" open>
          <summary className="cursor-pointer select-none px-3 py-2 text-sm font-medium text-foreground">
            PPD preview
          </summary>
          <pre className="text-xs overflow-auto p-3 whitespace-pre-wrap border-t border-border/50">{ppdText}</pre>
        </details>
      ) : null}
    </div>
  )
}
